### ISSUE TITLE
Support Chrome or Edge?

### ISSUE THREAD

**Issue by thoratica** [Assortment/darkmodejs#5]
Do this project support only FireFox? I can't use this on Chrome or Edge.

**Comment by lukewhitehouse** [comment]
Hey @thoratica, not yet unfortunately.

As mentioned in the [README under prerequisites](https://github.com/Assortment/darkmodejs#-prerequisites) we're limited by which browsers support the [`prefers-color-scheme`](https://caniuse.com/#search=prefers-color-scheme) media query.

Currently that's:
- Firefox v67+
- Safari v12.1+

**The good news is there will be support in Chrome and Edge in their next releases, Chrome 76 and Edge 76 🎉.**

Hopefully, this answers your questions so I'll close this. Let me know if you have any other questions.
